### ISSUE TITLE
Neovim: null-ls.nvim plugin

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#691]
[null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) is somewhat popular. We could integrate with it, even though quick-lint-js has a proper LSP server.

**Comment by even4void** [comment]
## Rationale
The advantage of proposing a builtin source rather than suggesting a custom handler for quick-lint-js is that it reduces the effort required by the user to configure a new JS linter. In addition, it can be used along LSP servers configured via nvim-lspconfig.

## Implementation
Here is a draft Lua file that uses quick-lint-js as a diagnostic source in null-ls.nvim. This file will be located in the `start` directory of Neovim package manager, e.g. `$HOME/.local/share/nvim/site/pack/packer/start/null-ls.nvim/lua/null-ls/builtins/diagnostics/quick_lint_js.lua`, when using [packer](https://github.com/wbthomason/packer.nvim)), once the PR to null-ls.nvim for this new builtin diagnostic source will be accepted. 

`null-ls.nvim/lua/null-ls/builtins/diagnostics/quick_lint_js.lua`:
```lua
local h = require("null-ls.helpers")
local methods = require("null-ls.methods")

local DIAGNOSTICS = methods.internal.DIAGNOSTICS

return h.make_builtin({
    name = "quick_lint_js",
    meta = {
        url = "https://github.com/quick-lint/quick-lint-js/",
        description = "quick-lint-js finds bugs in JavaScript programs.",
    },
    method = DIAGNOSTICS,
    filetypes = { "javascript" },
    generator_opts = {
        command = "quick-lint-js",
        args = { "--output-format", "vim-qflist-json", "$FILENAME" },
        to_stdin = true,
        format = "json",
        check_exit_code = function(c)
            return c <= 1
        end,
        on_output = function(params)
            local diags = {}
            for _, d in ipairs(params.output.qflist) do
                table.insert(diags, {
                    row = d.lnum,
                    end_row = d.end_lnum,
                    col = d.col,
                    end_col = d.end_col + 1,
                    code = d.nr,
                    message = d.text,
                    severity = d.type,
                })
            end
            return diags
        end,
    },
    factory = h.generator_factory,
})
```

## Installation

1. To setup null-ls.nvim in Neovim, install null-ls.nvim using packer (`use "jose-elias-alvarez/null-ls.nvim"`), or clone the repository and use the builtin `packadd` functionnality. 
2. Then, add the following to your config file (usually, `init.lua`).

```lua
require("null-ls").setup({
  sources = {
    null_ls.builtins.diagnostics.quick_lint_js,
  },
  -- the following is only required if you want to use an LSP server (e.g. tsserver) together with null-ls
  on_attach = function(client)
    if client.resolved_capabilities.document_formatting then
      vim.cmd([[
            augroup LspFormatting
                autocmd! * <buffer>
                autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
            augroup END
            ]])
    end
  end,
})
```
(Note that this assumes that the config file is managed in Lua and not Vimscript.)

Copy the file `quick_lint_js.lua` in the desired directory, then open a JS file.

## Test

I tested a [toy example](https://0x0.st/ocCf.js) from [CodeMirror](https://codemirror.net/demo/lint.html), and got the same diagnostics from null-ls.nvim as those obtained from either quick-lint-js LSP configured via nvim-lsconfig or the website [builtin checker](https://quick-lint-js.com/demo/).

```shell
~/tmp % quick-lint-js codemirror-sample.js                                                                                                                                                                          
codemirror-sample.js:4:39: error: nom de propriété manquant après l'opérateur '.' [E0142]
codemirror-sample.js:3:3: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:21:14: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:22:15: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:22:40: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:24:5: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:5:7: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:8:5: warning: utilisation d'une variable non déclarée : JSHINT [E0057]
codemirror-sample.js:8:12: warning: utilisation d'une variable non déclarée : editor [E0057]
codemirror-sample.js:9:25: warning: utilisation d'une variable non déclarée : JSHINT [E0057]
codemirror-sample.js:10:17: warning: utilisation d'une variable non déclarée : JSHINT [E0057]
codemirror-sample.js:18:20: warning: utilisation d'une variable non déclarée : editor [E0057]
```

Screenshot of Neovim (NVIM v0.8.0-dev) with Telescope diagnostics: https://imgur.com/a/aI9UPUk.

## Limitation

One minor annoyance is that when we create a blank JS file with Neovim, a warning message is displayed. Everything is fine otherwise. I will investigate this issue and let you know how to get ride of this warning message.

```
[null-ls] [WARN  22:38:07] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:78: failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:232: error in generator output: error
: failed to read from /home/chl/tmp/test.js: Aucun fichier ou dossier de ce type   
```

**Comment by strager** [comment]
Your script looks good so far. Some comments:

* Metadata URL should point to our website (https://quick-lint-js.com/), not to our GitHub repository.
* Add `javascriptreact` (.jsx files) to `filetypes`.
* Use quick-lint-js' `--path-for-config-search` option. Otherwise, `quick-lint-js.config` won't work.
* For now, I want to include this script in our quick-lint-js Vim plugin, not in null-ls.nvim. Is it okay to use `make_builtin` outside null-ls.nvim? Should we use a public API instead?

> One minor annoyance is that when we create a blank JS file with Neovim, a warning message is displayed.

Does this happen with other linters?

**Comment by even4void** [comment]
> * Metadata URL should point to our website (https://quick-lint-js.com/), not to our GitHub repository.
>
>  * Add `javascriptreact` (.jsx files) to `filetypes`.

Fixed the above two issues.

To keep in line with your qljs Vim plugin, I also added the following:

> [160× faster than ESLint](https://quick-lint-js.com/benchmarks/), quick-lint-js gives you instant feedback as you code.
> Find bugs in your JavaScript before your finger leaves the keyboard.
> Lint any JavaScript file with no configuration.
> See https://quick-lint-js.com/install/ for the installation documentation.

Please, let me know if this okay with you.

>  * Use quick-lint-js' `--path-for-config-search` option. Otherwise, `quick-lint-js.config` won't work.

Not sure about that. Is there a default path to discover config file? Originally, I did not add this option because null-ls.nvim offers a way to pass extra parameters in the source definition. For instance, this would read 

    null_ls.builtins.diagnostics.quick_lint_js.with({ extra_args = { "--path-for-config-search", "@@@" } }),

>  * For now, I want to include this script in our quick-lint-js Vim plugin, not in null-ls.nvim. Is it okay to use `make_builtin` outside null-ls.nvim? Should we use a public API instead?

null-ls.nvim uses the [unlicense](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/LICENSE), so I would say yes. By quickly glancing at the code, it looks like `make_builtin` does not not have external dependencies. However, I will need to check this more carefully since the license also states:

> This project uses modified and unmodified code from https://github.com/neovim/neovim and https://github.com/neovim/nvim-lspconfig, copyright Neovim contributors, licensed under the Apache 2.0 license, which can be obtained from http://www.apache.org/licenses/LICENSE-2.0.

Finally, I fixed the warning when opening empty file: `$FILENAME` was the culprit in the `args` parameter list, better to use `--stdin`.

**Comment by strager** [comment]
> To keep in line with your qljs Vim plugin, I also added the following: [...] Please, let me know if this okay with you.

Sounds good.

> Finally, I fixed the warning when opening empty file: `$FILENAME` was the culprit in the `args` parameter list, better to use `--stdin`.

Ah, I thought you were already using `--stdin`. I misread the code. My comment about `--path-for-config-search` only makes sense with `--stdin`.

> > * Use quick-lint-js' `--path-for-config-search` option. Otherwise, `quick-lint-js.config` won't work.
> 
> Not sure about that. Is there a default path to discover config file? Originally, I did not add this option because null-ls.nvim offers a way to pass extra parameters in the source definition. For instance, this would read
> 
> ```
> null_ls.builtins.diagnostics.quick_lint_js.with({ extra_args = { "--path-for-config-search", "@@@" } }),
> ```

I think you misunderstand the `--path-for-config-search` option. ESLint calls it `--stdin-filename`. See null-ls.nvim's ESLint integration here: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/a887bd6c1bb992ccf48e673b40e061c3e816204f/lua/null-ls/builtins/diagnostics/eslint.lua#L36

> null-ls.nvim uses the [unlicense](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/LICENSE), so I would say yes.

When I wrote "this script", I wasn't talking about including null-ls.nvim's source code in our repository, or distributing their source code. I was referring to the Lua code that *you* wrote.

**Comment by even4void** [comment]
> I think you misunderstand the `--path-for-config-search` option. ESLint calls it `--stdin-filename`.

Right. I misread your comment and I thought it was all about `--config-file=[FILE]` (qljs v2.4.0). In this case, we can pass additional parameters like in ESLint config, e.g.:

```lua
args = { "--output-format", "vim-qflist-json", "--stdin", "--path-for-config-search", "$FILENAME" },
```

> When I wrote "this script", I wasn't talking about including null-ls.nvim's source code in our repository, or distributing their source code. I was referring to the Lua code that _you_ wrote.

Of course, feel free to add and/or modify the Lua script. `make_builtin` will have to be rewritten to work without depending on null-ls.nvim. However, I can give it a try within the next few days.

**Comment by strager** [comment]
> `make_builtin` will have to be rewritten to work without depending on null-ls.nvim.

I don't want to avoid a dependency on null-ls.nvim. I want to avoid using *internal APIs* which are *subject to change without notice*. If `make_builtin` is supported for third-party plugins (such as ours), then I have no problem with us using `make_builtin`.

**Comment by strager** [comment]
@even4void Are you still working on this? Do you have the latest version uploaded somewhere?

**Comment by even4void** [comment]
Sorry, I've been busy before holidays, then somewhat sick for the past few weeks, and I didn't even noticed your last reply. Many bad reasons for which I apologize. Anyway, I rewrote the original snippet of code so that the Lua file now lives in the user config directory (instead of null-ls' own builtins directory -- which was okay for testing purpose only).

There's only one thing left: adding quick-lint-js' `--path-for-config-search` option at the end of the `args` table in the `generator_opts` table throws the following error with qljs v2.9 and older versions. I may be using that option the wrong way, though.

```
[null-ls] failed to run generator: ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error
 in generator output: error: unrecognized option: --path-for-config-search
```
The setup remains more or less the same as above. Below is the code I tested recently on qljs v2.5 and v2.9. Instructions described in point 2 will probably need some rewriting in the documentation.

**1--Diagnostic source** 
Set up the diagnostic source, `quick_lint_js`, in a separate file in your Neovim config (I use `$HOME/.config/nvim/lua/null_ls_extras.lua`) as follows:

```lua
local helpers = require("null-ls.helpers")
local methods = require("null-ls.methods")

local DIAGNOSTICS = methods.internal.DIAGNOSTICS

local M = {}

M.quick_lint_js = helpers.make_builtin({
  name = "quick_lint_js",
  meta = {
    url = "https://quick-lint-js.com/",
    description = "quick-lint-js finds bugs in JavaScript programs.",
    notes = {
      "[160× faster than ESLint](https://quick-lint-js.com/benchmarks/), quick-lint-js gives you instant feedback as you code.",
      "Find bugs in your JavaScript before your finger leaves the keyboard.",
      "Lint any JavaScript file with no configuration.",
      "See https://quick-lint-js.com/install/ for the installation documentation.",
    },
  },
  method = DIAGNOSTICS,
  filetypes = { "javascript", "javascriptreact" },
  generator_opts = {
    command = "quick-lint-js",
    args = { "--output-format", "vim-qflist-json", "--stdin" },
    to_stdin = true,
    format = "json",
    check_exit_code = function(c)
      return c <= 1
    end,
    on_output = function(params)
      local diags = {}
      for _, d in ipairs(params.output.qflist) do
        table.insert(diags, {
          row = d.lnum,
          end_row = d.end_lnum,
          col = d.col,
          end_col = d.end_col + 1,
          code = d.nr,
          message = d.text,
          severity = d.type,
        })
      end
      return diags
    end,
  },
  factory = helpers.generator_factory,
})

return M
```

This is the file you probably want to ship with new release of qljs. It could be located anywhere, we will just need to use the correct location in the setup suggested below.

**2--null-ls setup**
Declare the diagnostic source when setting up null-ls, e.g.

```lua
local null_ls = require("null-ls")
local null_ls_extras = require("null_ls_extras")

require("null-ls").setup({
  sources = {
    null_ls_extras.quick_lint_js,
  }
})
```

Of course, `require("null_ls_extras")` should reflect the correct location and filename of the code in point 1.

You can use and/or modify every piece of code to your liking, using the same license as qljs.

**Comment by k1ng440** [comment]
@strager, null-ls is being deprecated. See (null-ls.nvim#1621)[https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621]
